[package]
name = "lists"
version = "0.1.0"
authors = ["Eitan Adler <lists@eitanadler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
